### ISSUE TITLE
Wondering how spectrogram is drawn in the Readme

### ISSUE THREAD

**Issue by thu-zxs** [karolpiczak/ESC-50#1]
I've tried to reprduce it with python using matplotlib.pyplot.specgram, but can't get exactly the same figure, which seems to be a colormap problem. Great thanks if someone knows and tells me.

**Comment by karolpiczak** [comment]
The original code is available in the exploratory notebook:
https://github.com/karoldvl/paper-2015-esc-dataset/blob/master/Notebook/ESC-Dataset-for-Environmental-Sound-Classification.ipynb

Unfortunately, there have been some changes in how these colormaps are handled, so the images in the notebook are different from what you see in the readme. I could try checking the actual settings from the time I generated the readme image, but nowadays I would just start with the default for Matplotlib 2 - "viridis", unless there's a compelling reason not to do so.

**Comment by thu-zxs** [comment]
@karoldvl Thanks for the awesome notebook. I think colormaps from "librosa" also work for my tasks. Just don't bother if it's to much trouble. Great thanks again!
