### ISSUE TITLE
ESC-US subset

### ISSUE THREAD

**Issue by js0nwu** [karolpiczak/ESC-50#10]
Hello Karol,
I'm using another related dataset ESC-US and I just wanted to confirm that there isn't any overlap between the files in ESC-50 and the files in ESC-US? The paper seems to imply that they are separate but I wanted to ask for confirmation.

**Comment by karolpiczak** [comment]
Hi,

not exactly. There was a different process of acquiring data, but they all come from the same source (Freesound) in the end. ESC-US was downloaded automatically from `field-recording` tag, ESC-50 was done by hand searching through individual queries, but some of the source recordings might be used in both.

I've made a quick comparison of `esc50.csv` and `ESC-US.csv` and it seems that there might be some overlap between these source files. To be sure you would have to compare the actual contents - actual time slices for ESC-US extraction are provided in the CSV file, but I am not sure I can get them for ESC-50 right now. To be certain, I would just drop them from the unsupervised set.

filename | category | src_file
-- | -- | --
1-4211-A-12.wav | crackling_fire | 4211
1-5996-A-6.wav | hen | 5996
2-7321-A-33.wav | door_wood_creaks | 7321
1-7456-A-13.wav | crickets | 7456
1-11687-A-47.wav | airplane | 11687
1-13571-A-46.wav | church_bells | 13571
1-13572-A-46.wav | church_bells | 13572
1-15689-A-4.wav | frog | 15689
1-15689-B-4.wav | frog | 15689
1-16568-A-3.wav | cow | 16568
1-17092-A-27.wav | brushing_teeth | 17092
1-17092-B-27.wav | brushing_teeth | 17092
1-17150-A-12.wav | crackling_fire | 17150
1-17585-A-7.wav | insects | 17585
1-17970-A-4.wav | frog | 17970
1-18074-A-6.wav | hen | 18074
1-18074-B-6.wav | hen | 18074
1-18655-A-31.wav | mouse_click | 18655
1-18755-A-4.wav | frog | 18755
1-18755-B-4.wav | frog | 18755
1-18757-A-4.wav | frog | 18757
2-18766-A-12.wav | crackling_fire | 18766
2-18766-B-12.wav | crackling_fire | 18766
1-19501-A-7.wav | insects | 19501
1-21421-A-46.wav | church_bells | 21421
1-22804-A-46.wav | church_bells | 22804
1-23222-A-19.wav | thunderstorm | 23222
1-23222-B-19.wav | thunderstorm | 23222
1-23996-A-35.wav | washing_machine | 23996
1-23996-B-35.wav | washing_machine | 23996
1-24074-A-43.wav | car_horn | 24074
1-24076-A-43.wav | car_horn | 24076
1-24796-A-47.wav | airplane | 24796
1-25777-A-48.wav | fireworks | 25777
1-25781-A-48.wav | fireworks | 25781
1-26806-A-1.wav | rooster | 26806
1-27403-A-28.wav | snoring | 27403
1-27405-A-28.wav | snoring | 27405
2-28314-A-12.wav | crackling_fire | 28314
2-28314-B-12.wav | crackling_fire | 28314
1-28808-A-43.wav | car_horn | 28808
1-29561-A-10.wav | rain | 29561
1-30039-A-26.wav | laughing | 30039
1-30043-A-26.wav | laughing | 30043
1-30226-A-0.wav | dog | 30226
2-30322-A-12.wav | crackling_fire | 30322
2-30322-B-12.wav | crackling_fire | 30322
1-30830-A-24.wav | coughing | 30830
1-31251-A-6.wav | hen | 31251
1-31251-B-6.wav | hen | 31251
1-31482-A-42.wav | siren | 31482
1-31482-B-42.wav | siren | 31482
1-31836-A-4.wav | frog | 31836
1-31836-B-4.wav | frog | 31836
2-32515-A-4.wav | frog | 32515
2-32515-B-4.wav | frog | 32515
2-32515-C-4.wav | frog | 32515
2-32515-D-4.wav | frog | 32515
2-32834-A-4.wav | frog | 32834
1-34094-A-5.wav | cat | 34094
1-34094-B-5.wav | cat | 34094
1-38559-A-14.wav | chirping_birds | 38559
1-38560-A-14.wav | chirping_birds | 38560
2-39441-A-19.wav | thunderstorm | 39441
2-39443-A-19.wav | thunderstorm | 39443
2-39443-B-19.wav | thunderstorm | 39443
2-39945-A-19.wav | thunderstorm | 39945
2-39945-B-19.wav | thunderstorm | 39945
2-39945-C-19.wav | thunderstorm | 39945
1-40621-A-28.wav | snoring | 40621
2-42101-A-43.wav | car_horn | 42101
1-43760-A-11.wav | sea_waves | 43760
1-44831-A-1.wav | rooster | 44831
1-46040-A-14.wav | chirping_birds | 46040
1-46938-A-7.wav | insects | 46938
1-46938-B-7.wav | insects | 46938
1-49409-A-8.wav | sheep | 49409
1-49409-B-8.wav | sheep | 49409
1-50060-A-10.wav | rain | 50060
1-51035-A-16.wav | wind | 51035
1-51036-A-16.wav | wind | 51036
1-51037-A-16.wav | wind | 51037
3-51376-A-42.wav | siren | 51376
2-52789-A-4.wav | frog | 52789
1-53467-A-47.wav | airplane | 53467
1-54747-A-46.wav | church_bells | 54747
1-54918-A-14.wav | chirping_birds | 54918
1-54918-B-14.wav | chirping_birds | 54918
1-54958-A-10.wav | rain | 54958
1-56233-A-9.wav | crow | 56233
1-56907-A-46.wav | church_bells | 56907
1-58277-A-3.wav | cow | 58277
3-58772-A-42.wav | siren | 58772
1-61252-A-11.wav | sea_waves | 61252
2-61311-A-12.wav | crackling_fire | 61311
5-61635-A-8.wav | sheep | 61635
1-62509-A-45.wav | train | 62509
1-62849-A-38.wav | clock_tick | 62849
1-62850-A-38.wav | clock_tick | 62850
1-64398-A-41.wav | chainsaw | 64398
1-64398-B-41.wav | chainsaw | 64398
2-65747-A-12.wav | crackling_fire | 65747
3-65748-A-12.wav | crackling_fire | 65748
1-69422-A-3.wav | cow | 69422
1-69760-A-16.wav | wind | 69760
1-70300-A-45.wav | train | 70300
2-71162-A-1.wav | rooster | 71162
3-71964-A-4.wav | frog | 71964
3-71964-B-4.wav | frog | 71964
3-71964-C-4.wav | frog | 71964
1-72229-A-6.wav | hen | 72229
1-72229-B-6.wav | hen | 72229
2-72268-A-6.wav | hen | 72268
2-72547-A-14.wav | chirping_birds | 72547
2-72547-B-14.wav | chirping_birds | 72547
2-72547-C-14.wav | chirping_birds | 72547
2-72547-D-14.wav | chirping_birds | 72547
2-73260-A-10.wav | rain | 73260
1-74517-A-37.wav | clock_alarm | 74517
2-78781-A-47.wav | airplane | 78781
2-78799-A-47.wav | airplane | 78799
2-80313-A-28.wav | snoring | 80313
2-80844-A-13.wav | crickets | 80844
2-83934-A-5.wav | cat | 83934
2-83934-B-5.wav | cat | 83934
1-85362-A-0.wav | dog | 85362
1-88409-A-45.wav | train | 88409
1-88409-B-45.wav | train | 88409
1-88574-A-8.wav | sheep | 88574
2-95035-A-1.wav | rooster | 95035
3-95694-A-5.wav | cat | 95694
3-95695-A-5.wav | cat | 95695
3-95695-B-5.wav | cat | 95695
3-95697-A-5.wav | cat | 95697
2-96033-A-13.wav | crickets | 96033
2-96654-A-47.wav | airplane | 96654
1-96950-A-9.wav | crow | 96950
1-96950-B-9.wav | crow | 96950
3-98869-A-46.wav | church_bells | 98869
4-102844-A-49.wav | hand_saw | 102844
4-102844-B-49.wav | hand_saw | 102844
4-102844-C-49.wav | hand_saw | 102844
2-102852-A-11.wav | sea_waves | 102852
4-102871-A-42.wav | siren | 102871
3-102908-A-4.wav | frog | 102908
3-103050-A-19.wav | thunderstorm | 103050
3-103051-A-19.wav | thunderstorm | 103051
3-103051-B-19.wav | thunderstorm | 103051
3-103051-C-19.wav | thunderstorm | 103051
1-103298-A-9.wav | crow | 103298
5-103415-A-2.wav | pig | 103415
5-103416-A-2.wav | pig | 103416
5-103418-A-2.wav | pig | 103418
5-103420-A-2.wav | pig | 103420
5-103421-A-2.wav | pig | 103421
2-103423-A-3.wav | cow | 103423
2-103424-A-3.wav | cow | 103424
2-103426-A-3.wav | cow | 103426
2-103427-A-3.wav | cow | 103427
2-103428-A-3.wav | cow | 103428
3-104761-A-7.wav | insects | 104761
3-104761-B-7.wav | insects | 104761
3-105235-A-7.wav | insects | 105235
3-105236-A-7.wav | insects | 105236
2-105270-A-47.wav | airplane | 105270
2-106849-A-47.wav | airplane | 106849
2-108760-A-14.wav | chirping_birds | 108760
2-108760-B-14.wav | chirping_birds | 108760
2-108761-A-14.wav | chirping_birds | 108761
2-108763-A-9.wav | crow | 108763
2-108766-A-9.wav | crow | 108766
2-108767-A-9.wav | crow | 108767
2-108767-B-9.wav | crow | 108767
2-108767-C-9.wav | crow | 108767
2-109231-A-9.wav | crow | 109231
2-109231-B-9.wav | crow | 109231
2-109231-C-9.wav | crow | 109231
2-109371-A-16.wav | wind | 109371
2-109371-B-16.wav | wind | 109371
2-109371-C-16.wav | wind | 109371
2-109371-D-16.wav | wind | 109371
2-109374-A-16.wav | wind | 109374
3-110913-A-7.wav | insects | 110913
3-110913-B-7.wav | insects | 110913
3-110913-C-7.wav | insects | 110913
3-110913-D-7.wav | insects | 110913
3-111102-A-46.wav | church_bells | 111102
3-111102-B-46.wav | church_bells | 111102
3-112397-A-9.wav | crow | 112397
3-115387-A-47.wav | airplane | 115387
3-115387-B-47.wav | airplane | 115387
3-115387-C-47.wav | airplane | 115387
1-115521-A-19.wav | thunderstorm | 115521
2-116400-A-0.wav | dog | 116400
1-119125-A-45.wav | train | 119125
2-120586-A-6.wav | hen | 120586
2-120587-A-6.wav | hen | 120587
3-121348-A-9.wav | crow | 121348
4-121532-A-42.wav | siren | 121532
2-122066-A-45.wav | train | 122066
2-122066-B-45.wav | train | 122066
2-122067-A-45.wav | train | 122067
2-122067-B-45.wav | train | 122067
2-122616-A-14.wav | chirping_birds | 122616
2-122820-A-36.wav | vacuum_cleaner | 122820
2-122820-B-36.wav | vacuum_cleaner | 122820
3-123224-A-19.wav | thunderstorm | 123224
3-124376-A-3.wav | cow | 124376
3-124376-B-3.wav | cow | 124376
3-124600-A-19.wav | thunderstorm | 124600
4-125070-A-19.wav | thunderstorm | 125070
4-125071-A-19.wav | thunderstorm | 125071
4-125072-A-19.wav | thunderstorm | 125072
4-125072-B-19.wav | thunderstorm | 125072
2-125821-A-13.wav | crickets | 125821
4-125825-A-46.wav | church_bells | 125825
4-125825-B-46.wav | church_bells | 125825
4-126046-A-18.wav | toilet_flush | 126046
3-127890-A-9.wav | crow | 127890
3-127890-B-9.wav | crow | 127890
3-127890-C-9.wav | crow | 127890
2-128465-A-43.wav | car_horn | 128465
2-128465-B-43.wav | car_horn | 128465
3-128512-A-47.wav | airplane | 128512
3-128512-B-47.wav | airplane | 128512
3-129338-A-13.wav | crickets | 129338
4-130584-A-4.wav | frog | 130584
3-132852-A-10.wav | rain | 132852
2-134049-A-6.wav | hen | 134049
3-134049-A-1.wav | rooster | 134049
3-134699-A-16.wav | wind | 134699
3-134699-B-16.wav | wind | 134699
3-134699-C-16.wav | wind | 134699
2-134700-A-38.wav | clock_tick | 134700
2-135649-A-45.wav | train | 135649
2-135649-B-45.wav | train | 135649
2-135649-C-45.wav | train | 135649
3-135650-A-45.wav | train | 135650
3-135650-B-45.wav | train | 135650
4-136381-A-9.wav | crow | 136381
3-137152-A-1.wav | rooster | 137152
2-138465-A-43.wav | car_horn | 138465
4-140034-A-46.wav | church_bells | 140034
4-144083-A-16.wav | wind | 144083
4-144083-B-16.wav | wind | 144083
4-144083-C-16.wav | wind | 144083
4-144085-A-16.wav | wind | 144085
2-144137-A-43.wav | car_horn | 144137
3-144891-A-19.wav | thunderstorm | 144891
3-144891-B-19.wav | thunderstorm | 144891
4-145081-A-9.wav | crow | 145081
3-145487-A-24.wav | coughing | 145487
3-145577-A-43.wav | car_horn | 145577
4-146200-A-36.wav | vacuum_cleaner | 146200
3-146697-A-43.wav | car_horn | 146697
4-147240-A-2.wav | pig | 147240
4-147240-B-2.wav | pig | 147240
4-147657-A-46.wav | church_bells | 147657
4-147658-A-46.wav | church_bells | 147658
4-149294-A-41.wav | chainsaw | 149294
4-149294-B-41.wav | chainsaw | 149294
4-150364-A-46.wav | church_bells | 150364
4-150364-B-46.wav | church_bells | 150364
3-151255-A-28.wav | snoring | 151255
3-152039-A-3.wav | cow | 152039
3-152039-B-3.wav | cow | 152039
4-154793-A-4.wav | frog | 154793
3-155130-A-43.wav | car_horn | 155130
3-155234-A-43.wav | car_horn | 155234
3-155577-A-14.wav | chirping_birds | 155577
3-155578-A-14.wav | chirping_birds | 155578
3-155579-A-14.wav | chirping_birds | 155579
3-155583-A-14.wav | chirping_birds | 155583
3-155584-A-14.wav | chirping_birds | 155584
4-156227-A-9.wav | crow | 156227
2-157488-A-6.wav | hen | 157488
3-157492-A-45.wav | train | 157492
4-157611-A-41.wav | chainsaw | 157611
4-157611-B-41.wav | chainsaw | 157611
3-157615-A-10.wav | rain | 157615
3-157695-A-0.wav | dog | 157695
4-159426-A-9.wav | crow | 159426
4-159609-A-14.wav | chirping_birds | 159609
4-159609-B-14.wav | chirping_birds | 159609
5-160551-A-42.wav | siren | 160551
1-160563-A-48.wav | fireworks | 160563
1-160563-B-48.wav | fireworks | 160563
5-160614-A-48.wav | fireworks | 160614
5-160614-B-48.wav | fireworks | 160614
5-160614-C-48.wav | fireworks | 160614
5-160614-D-48.wav | fireworks | 160614
5-160614-E-48.wav | fireworks | 160614
5-160614-F-48.wav | fireworks | 160614
5-160614-G-48.wav | fireworks | 160614
5-160614-H-48.wav | fireworks | 160614
4-161519-A-19.wav | thunderstorm | 161519
4-163264-A-10.wav | rain | 163264
3-164120-A-11.wav | sea_waves | 164120
4-164206-A-10.wav | rain | 164206
4-165813-A-19.wav | thunderstorm | 165813
4-165813-B-19.wav | thunderstorm | 165813
3-165856-A-41.wav | chainsaw | 165856
4-166661-A-10.wav | rain | 166661
4-167063-A-11.wav | sea_waves | 167063
4-167063-B-11.wav | sea_waves | 167063
4-167063-C-11.wav | sea_waves | 167063
4-170078-A-1.wav | rooster | 170078
5-170338-A-41.wav | chainsaw | 170338
5-170338-B-41.wav | chainsaw | 170338
3-171012-A-38.wav | clock_tick | 171012
4-171652-A-44.wav | engine | 171652
1-172649-A-40.wav | helicopter | 172649
1-172649-B-40.wav | helicopter | 172649
1-172649-C-40.wav | helicopter | 172649
1-172649-D-40.wav | helicopter | 172649
1-172649-E-40.wav | helicopter | 172649
1-172649-F-40.wav | helicopter | 172649
3-172881-A-48.wav | fireworks | 172881
3-172922-A-48.wav | fireworks | 172922
4-173865-A-9.wav | crow | 173865
4-173865-B-9.wav | crow | 173865
4-174860-A-3.wav | cow | 174860
4-174860-B-3.wav | cow | 174860
3-178096-A-6.wav | hen | 178096
1-181071-A-40.wav | helicopter | 181071
1-181071-B-40.wav | helicopter | 181071
4-181362-A-13.wav | crickets | 181362
5-181766-A-10.wav | rain | 181766
4-184235-A-28.wav | snoring | 184235
4-184237-A-28.wav | snoring | 184237
4-186518-A-30.wav | door_wood_knock | 186518
3-187710-A-11.wav | sea_waves | 187710
4-187769-A-14.wav | chirping_birds | 187769
4-187769-B-14.wav | chirping_birds | 187769
5-188495-A-19.wav | thunderstorm | 188495
4-188703-A-8.wav | sheep | 188703
4-188703-B-8.wav | sheep | 188703
4-188703-C-8.wav | sheep | 188703
4-188703-D-8.wav | sheep | 188703
5-189237-A-12.wav | crackling_fire | 189237
4-189830-A-22.wav | clapping | 189830
5-191497-A-33.wav | door_wood_creaks | 191497
5-192191-A-19.wav | thunderstorm | 192191
4-193480-A-40.wav | helicopter | 193480
4-193480-B-40.wav | helicopter | 193480
5-195557-A-19.wav | thunderstorm | 195557
5-197988-A-46.wav | church_bells | 197988
5-198321-A-10.wav | rain | 198321
5-199284-A-45.wav | train | 199284
5-199284-B-45.wav | train | 199284
5-201172-A-46.wav | church_bells | 201172
4-202749-A-13.wav | crickets | 202749
5-203128-A-0.wav | dog | 203128
5-203128-B-0.wav | dog | 203128
4-204115-A-39.wav | glass_breaking | 204115
4-204119-A-39.wav | glass_breaking | 204119
4-204121-A-39.wav | glass_breaking | 204121
4-204123-A-39.wav | glass_breaking | 204123
4-204618-A-11.wav | sea_waves | 204618
5-204741-A-46.wav | church_bells | 204741
4-210309-A-31.wav | mouse_click | 210309
5-212454-A-0.wav | dog | 212454
5-213077-A-11.wav | sea_waves | 213077
5-213836-A-9.wav | crow | 213836
5-213836-B-9.wav | crow | 213836
5-213836-C-9.wav | crow | 213836
5-213836-D-9.wav | crow | 213836
5-214362-A-17.wav | pouring_water | 214362
5-215172-A-13.wav | crickets | 215172
5-215179-A-13.wav | crickets | 215179
5-215445-A-47.wav | airplane | 215445
5-215447-A-47.wav | airplane | 215447
5-215449-A-47.wav | airplane | 215449
4-215635-A-34.wav | can_opening | 215635
5-215658-A-12.wav | crackling_fire | 215658
5-215658-B-12.wav | crackling_fire | 215658
4-216211-A-14.wav | chirping_birds | 216211
5-219379-A-11.wav | sea_waves | 219379
5-219379-B-11.wav | sea_waves | 219379
5-219379-C-11.wav | sea_waves | 219379
5-222041-A-9.wav | crow | 222041
5-222524-A-41.wav | chainsaw | 222524
3-233151-A-2.wav | pig | 233151
5-233160-A-1.wav | rooster | 233160
4-234644-A-2.wav | pig | 234644
4-234879-A-6.wav | hen | 234879
5-234879-A-1.wav | rooster | 234879
5-234879-B-1.wav | rooster | 234879
5-237499-A-4.wav | frog | 237499
5-242492-A-3.wav | cow | 242492
5-242711-A-9.wav | crow | 242711
5-243448-A-14.wav | chirping_birds | 243448
5-243449-A-14.wav | chirping_birds | 243449
3-243726-A-43.wav | car_horn | 243726
5-244310-A-25.wav | footsteps | 244310
5-244315-A-6.wav | hen | 244315
5-244315-B-6.wav | hen | 244315
5-244315-C-6.wav | hen | 244315
4-244318-A-6.wav | hen | 244318
5-245040-A-35.wav | washing_machine | 245040
3-246513-A-16.wav | wind | 246513
3-246513-B-16.wav | wind | 246513
5-248341-A-6.wav | hen | 248341
5-248341-B-6.wav | hen | 248341
5-248341-C-6.wav | hen | 248341
4-250864-A-8.wav | sheep | 250864
4-250869-A-2.wav | pig | 250869
4-250869-B-2.wav | pig | 250869
4-250869-C-2.wav | pig | 250869
5-251957-A-47.wav | airplane | 251957
4-251959-A-47.wav | airplane | 251959
5-251962-A-47.wav | airplane | 251962
5-251963-A-47.wav | airplane | 251963
5-251971-A-47.wav | airplane | 251971
3-253081-A-2.wav | pig | 253081
3-253084-A-2.wav | pig | 253084
3-253084-B-2.wav | pig | 253084
3-253084-C-2.wav | pig | 253084
3-253084-D-2.wav | pig | 253084
3-253084-E-2.wav | pig | 253084
5-253094-A-49.wav | hand_saw | 253094
5-253094-B-49.wav | hand_saw | 253094
5-253094-C-49.wav | hand_saw | 253094
5-253094-D-49.wav | hand_saw | 253094
5-253101-A-49.wav | hand_saw | 253101
5-253101-B-49.wav | hand_saw | 253101
5-253101-C-49.wav | hand_saw | 253101
4-253649-A-6.wav | hen | 253649
1-254507-A-43.wav | car_horn | 254507
4-255371-A-47.wav | airplane | 255371
5-257839-A-14.wav | chirping_birds | 257839
5-260433-A-39.wav | glass_breaking | 260433
5-260434-A-39.wav | glass_breaking | 260434
5-262641-A-15.wav | water_drops | 262641

**Comment by js0nwu** [comment]
Thanks for the response! I will exclude those overlapping files from my experiments then.
