### ISSUE TITLE
Seperately categorize cough and sneeze

### ISSUE THREAD

**Issue by sundar19** [karolpiczak/ESC-50#11]
Is there any ways to seperately categorize only cough and sneeze sounds to train? them I am using pytorch to train datasets. Do I have to categorize using pandas?

**Comment by karolpiczak** [comment]
I am not exactly sure what is the actual outcome you want, but labels for each file are available in [`esc50.csv`](https://github.com/karolpiczak/ESC-50/blob/master/meta/esc50.csv) - you can extract only the files you are interested in using the provided labels (`coughing -> 24`, `sneezing -> 21`).

**Comment by sundar19** [comment]
Thank you so much
