### ISSUE TITLE
How to divide the dataset into train/val/test?

### ISSUE THREAD

**Issue by fake-warrior8** [karolpiczak/ESC-50#18]
Hi, I'd like to know how to divide the dataset into train/val/test. It seems to be divided as train/val=8:1. Is this true?

**Comment by karolpiczak** [comment]
Hi, I am not sure why my previous e-mail reply didn't go through, I missed that.

There are no predefined train/test splits, but the dataset is split into 5 folds of equal size.

A common procedure is to use 4 folds for training and 1 for testing, and perform this 5 times for cross-validation (by switching the fold used for testing). If you need additional validation, you can use 3 folds for training, 1 for validation and 1 for testing.

**Comment by karolpiczak** [comment]
There are no predefined train/test splits, but the dataset is split into 5
folds of equal size.

A common procedure is to use 4 folds for training and 1 for testing, and
perform this 5 times for cross-validation (by switching the fold used for
testing). If you need validation, you can use 3 folds for training, 1 for
validation and 1 for testing.

**Comment by fake-warrior8** [comment]
Thank you for your reply!
