### ISSUE TITLE
License of ESC-US

### ISSUE THREAD

**Issue by LJ-water** [karolpiczak/ESC-50#21]
Hi, thanks for sharing this amazing work. 

I'd like to use **ESC-US** for my demo (which could be commercial) but couldn't find the license. Could you please let me know which license is applied to ESC-US? 

Thanks!

**Comment by karolpiczak** [comment]
Hi,

the ESC-US part of the dataset was published under the terms of the Creative Commons Attribution-NonCommercial license (http://creativecommons.org/licenses/by-nc/3.0/). In the `ESC-US.csv` you can check the original license for each of the recordings. You are free to use the individual files according to their original licensing terms, i.e. for files with `http://creativecommons.org/licenses/by/3.0/` you should be fine even in commercial demos.

**Comment by LJ-water** [comment]
Thank you!
