### ISSUE TITLE
How to track particular sound class data 

### ISSUE THREAD

**Issue by prashanthkolaneru** [karolpiczak/ESC-50#7]
The data set consist of 2000 audio sounds, but i am interested in sounds classes like traffic sounds, helicopter making sounds, human sounds. how to track that particular classes.
tha data is not arranges as classes, it is mixed.

**Comment by karolpiczak** [comment]
I'm not exactly sure what you mean. There are 50 audio classes as stated in
the description. Class assignments for individual files can be found in the
CSV file. No additional categorization is provided. You could have a look
at Freesound/Freesound Datasets for further data.

>

**Comment by prashanthkolaneru** [comment]
I need individual audio files of domestic sounds, vechicle horn sounds, dog
barking.

**Comment by karolpiczak** [comment]
In that case I think looking at Freesound might be the best way to aquire
additional data.

**Comment by prashanthkolaneru** [comment]
I want your 50 classes of sound dataset
50 different folders like each class considered as one folder.
Can it possible sir.
It might help me to do my work in easy way.

**Comment by karolpiczak** [comment]
You could try downloading an old version of the dataset at:
https://github.com/karoldvl/ESC-50/archive/ec6f9e3188b65e75e05caed87929c727a12553d9.zip

**Comment by prashanthkolaneru** [comment]
Thank you i will check with it.
