### ISSUE TITLE
ESC on Android

### ISSUE THREAD

**Issue by baoqianyue** [karolpiczak/ESC-50#8]
Is there a better ESC project on the android platform?

Appreciate you!

**Comment by karolpiczak** [comment]
You could try contacting the authors of this paper (https://www.cs.tut.fi/sgn/arg/dcase2016/documents/workshop/Pillos-DCASE2016workshop.pdf) as they have more experience in mobile sound classification.

**Comment by baoqianyue** [comment]
👌
